"""empty message

Revision ID: 493eeecf281b
Revises: daca6dbbcb3f
Create Date: 2023-02-26 18:31:34.220758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493eeecf281b'
down_revision = 'daca6dbbcb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
